Varoita tulosluettelossa, jos vartio saa tehtävästä enemmän kuin tehtävän max pisteet
partio-scout/kipa pull request #21
Opened 2021-10-03 08:08 UTC by villevuor

Lisää tulosluetteloon varoitus, jos vartio saa yli max pisteet tehtävästä. (Tämä voi olla mahdollista, jos kaava on tehty väärin.) 

Tulospäällikkö voi pelastaa nahkansa ja tarkistaa kaavat ennen julkista nöyryytystä.

2021-10-03 08:10 UTC, villevuor commented
Rivillä ~300 oleelliset muutokset, tuli näköjään rivinvaihtojen siistimisiä samalla

2021-10-03 10:02 UTC, ZeiP requested changes

2021-10-03 10:02 UTC, ZeiP commented on web/tupa/TulosLaskin.py
> +                        if (pisteet and type(pisteet) != str and type(pisteet) != unicode) :
Tähän voisi kommentoida, miksi pisteet eivät olisi numero. Johtuiko tämä hylkäyksestä / keskeytyksestä vai tuliko muitakin tällaisia?

2021-10-05 06:11 UTC, villevuor commented
Joo-o täytyy tästäkin tarkistaa nuo testit vielä

2022-02-25 16:33 UTC, ZeiP approved these changes

2022-02-25 16:33 UTC, merged

2022-02-25 16:33 UTC, ZeiP commented
Kiitos, hienoa että tämäkin feature tuli vihdoin tehtyä!