CONTRIBUTING.md
partio-scout/kipa pull request #42
Opened 2024-03-04 21:38 UTC by ilesoft

Alustava ehdotus Kipan kehityksen ohjeiksi.

Pyydän palautetta, keskustelua ja lisäysehdotuksia @ZeiP @vaaralav.

2024-03-05 07:03 UTC, ilesoft commented on CONTRIBUTING.md
> +Koodissa, kommenteissa, commiteissa ja tiedostonimissä olisi hyvä pyrkiä käyttämään englantie. Englanti on luonteva valinta jo pelkästään Pythonin englantimaisuuden takia. Koodi tosin on monessa koht
Typo: englatie

2024-03-05 20:59 UTC, vaaralav commented on CONTRIBUTING.md
> +Mahdolliset viitteet GitHubin issueen tai pull requestiin kuuluvat commit-viestin bodyyn. Yleinen historian tarkastelu on helpompaa kun graafeissa olevat commit-viestien otsikot eivät ole täynnä link
Ite tykkään enempi siitä, että issueen viitataan heti commit messagen (tallennusviestin?) kärkeen

2024-03-05 21:02 UTC, vaaralav commented on CONTRIBUTING.md
> +Tätä merge-strategiaa kutsutaan nimellä "semi linear merge". Azure DevOps:issa voi tämän strategian asettaa käyttöön repositoriotasolla, mutta githubissa ei ole erillistä toimintoa tätä varten.
👍 semi linear merge

2024-03-05 21:06 UTC, vaaralav commented on CONTRIBUTING.md
> +Mahdolliset viitteet GitHubin issueen tai pull requestiin kuuluvat commit-viestin bodyyn. Yleinen historian tarkastelu on helpompaa kun graafeissa olevat commit-viestien otsikot eivät ole täynnä link
Yleisin case itsellä katsella historiaa on blame editorissa, josta haluan hypätä tickettiin tai PR:ään mahdollisimman helposti. Ehkä ajatuksena niin, että se kokonaisuus johon commit kuuluu on oleellisempaa kuin yhden commitin hyvin muotoiltu commit message.

2024-03-06 19:04 UTC, ilesoft commented on CONTRIBUTING.md
> +Mahdolliset viitteet GitHubin issueen tai pull requestiin kuuluvat commit-viestin bodyyn. Yleinen historian tarkastelu on helpompaa kun graafeissa olevat commit-viestien otsikot eivät ole täynnä link
Tuo "kokonaisuus johon commit kuuluu" on munkin mielestä yksi tärkeimpiä seikkoja. Ja sen kokonaisuuden jääminen historiaan varmistetaan tavalla, jota koitin kuvata tuossa kohdassa  [Tapaus 2: Ominaisuus kuuluu useampaan committiin](https://github.com/partio-scout/kipa/blob/contribution-guidelines/CONTRIBUTING.md#tapaus-2-ominaisuus-kuuluu-useampaan-committiin).

Mulla usein työprojekteissa kuin tässä kipassakin on sellainen tilanne, että alkuperäiseen tiketöintijärjestelmään/speksiin ei ole enää pääsyä ta sitä ei ole enää olemassa. Ja kun systeemejä on koodattu ajatuksella että "tarkemmat tiedot löytyy sitten githubista" niin tuloksena on kohtalaisen hyödyttömiä git-historioita. Tämän takia suhtaudun koodin ja committiviestien (ja erityisesti merge-comittien viestien) kirjoittamiseen ikään kuin lukijalla ei olisi mahdollisuutta päästä githubiin yms.

2024-03-06 19:19 UTC, ilesoft commented on CONTRIBUTING.md
> +Mahdolliset viitteet GitHubin issueen tai pull requestiin kuuluvat commit-viestin bodyyn. Yleinen historian tarkastelu on helpompaa kun graafeissa olevat commit-viestien otsikot eivät ole täynnä link
Mullakin on tosiaan paha tapa pitää IDE:ssä kokoajan blame-näkymää koodin vieressä auki

2024-03-06 19:25 UTC, ilesoft commented on CONTRIBUTING.md
> +Mahdolliset viitteet GitHubin issueen tai pull requestiin kuuluvat commit-viestin bodyyn. Yleinen historian tarkastelu on helpompaa kun graafeissa olevat commit-viestien otsikot eivät ole täynnä link
Voisin vielä vähän tarkistaa tota tekstä niin että toi ajatus noitten issuelinkkien lisäämisestä sinne description-osuuteen tulisi paremmin ilmi.

2024-03-11 09:42 UTC, ZeiP commented on CONTRIBUTING.md
> +Mahdolliset viitteet GitHubin issueen tai pull requestiin kuuluvat commit-viestin bodyyn. Yleinen historian tarkastelu on helpompaa kun graafeissa olevat commit-viestien otsikot eivät ole täynnä link
Itsekin isommissa projekteissa tuppaan olettamaan että tikettinumero on heti commit-viestin ekan rivin eli ”otsikon” aluksi, jolloin näkee helposti mistä saa lisätietoja. Commit-viestiinkin on hyvä panostaa ja lähtökohta siitä, että tiketit eivät välttämättä ole tulevaisuudessa enää käytössä, on varsin relevantti, eli sikäli kuulostaa minusta hyvältä muuten!

2024-03-11 09:48 UTC, ZeiP commented on CONTRIBUTING.md
> +Tätä merge-strategiaa kutsutaan nimellä "semi linear merge". Azure DevOps:issa voi tämän strategian asettaa käyttöön repositoriotasolla, mutta githubissa ei ole erillistä toimintoa tätä varten.
Committien säilyttäminen on itselleni ehkä se olennaisin juttu, en ihan hirveästi välitä squashaamisesta vaikka silläkin on hyvät puolensa. Melkein tekisi mieli mennä näissä helppoudella – ymmärränkö siis oikein että semi-linear merge tehdään Githubissa niin että tehdään feature-haaralle rebase ja sitten mergetään PR normaalisti? En pitäisi tuota rebasea välttämättömänä edellytyksenä, mutta toki hyvänä käytäntönä.

Pohdin myös, onko välttämättä tarpeellista määrittää omaa toimintatapaansa yhden commitin PR:ille vai olisiko kuitenkin ok että niissäkin on merge commit. Minusta sitä ei tarvita, mutta kun eri merge-tapojen automaattinen valinta ei taida onnistua niin en tekisi kovin ehdottomia sääntöjä (ennakoiden että ainakin itse unohdan ne)

2024-03-11 09:49 UTC, ZeiP requested changes
Noita paria avointa keskustelua voisi jatkaa, mutta muuten ehdottomasti ok!

2024-03-11 11:08 UTC, ilesoft commented on CONTRIBUTING.md
> +Mahdolliset viitteet GitHubin issueen tai pull requestiin kuuluvat commit-viestin bodyyn. Yleinen historian tarkastelu on helpompaa kun graafeissa olevat commit-viestien otsikot eivät ole täynnä link
Tuo issuenumeron sijainti taitaa olla lähinnä tottumiskysymys ja tärkeintä on kuitenkin yhdenmukaisuus projektin sisällä. Päivitin tota vähän.

2024-03-11 11:15 UTC, ilesoft commented on CONTRIBUTING.md
> +Tätä merge-strategiaa kutsutaan nimellä "semi linear merge". Azure DevOps:issa voi tämän strategian asettaa käyttöön repositoriotasolla, mutta githubissa ei ole erillistä toimintoa tätä varten.
Tätä mietin itsekkin

2024-03-11 11:18 UTC, ilesoft commented on CONTRIBUTING.md
> +Tätä merge-strategiaa kutsutaan nimellä "semi linear merge". Azure DevOps:issa voi tämän strategian asettaa käyttöön repositoriotasolla, mutta githubissa ei ole erillistä toimintoa tätä varten.
Sitä puoltaa sekin, että se saadaan otettua tuolta githubin asetuksista ylimääräiset merge-tavat pois käytöstä-

2024-03-11 11:19 UTC, ilesoft commented on CONTRIBUTING.md
> +Tätä merge-strategiaa kutsutaan nimellä "semi linear merge". Azure DevOps:issa voi tämän strategian asettaa käyttöön repositoriotasolla, mutta githubissa ei ole erillistä toimintoa tätä varten.
Ja toki yksinkertainen ohje on helpompi

2024-03-12 12:20 UTC, ZeiP approved these changes

2024-03-12 12:44 UTC, merged