Ylimääräisten tiedostojen poistoa
partio-scout/kipa pull request #46
Opened 2024-03-25 04:22 UTC by ilesoft

* Ylimääräiset ja/tai ristiriitaiset lisenssitiedostot
* tyhjä hakemisto
* kahdennettu generate_passwords
* eclipse-projektitiedosto, ehkä
* IE-CSS

2024-03-25 09:41 UTC, ilesoft commented
Oho, joku meni poikittain. Samalla tuli myöskin huomatuksi, että noi jobit vois tykätä jostain hiukan lyhyemmästä timeoutista.

2024-04-04 12:47 UTC, ZeiP requested changes

2024-04-04 12:47 UTC, ZeiP commented on db/.keep
The idea here is to make sure the database directory is present. Is there still a reference for the db directory somewhere in the config?

2024-04-04 14:06 UTC, ZeiP approved these changes

2024-04-04 15:36 UTC, merged