Dokumentaation uudelleenjärjestely
partio-scout/kipa pull request #68
Opened 2024-11-28 19:51 UTC by ilesoft

2024-11-29 15:49 UTC, pholm approved these changes

2024-12-02 19:04 UTC, pholm requested changes
Muutoksin ok

2024-12-02 19:04 UTC, pholm commented on docs/manual.md
> +ohjelmisto. Kipa on helppokäyttäinen ja se on vapaasti levitettävissä sekä
```suggestion
ohjelmisto. Kipa on helppokäyttöinen ja se on vapaasti levitettävissä sekä
```

2024-12-02 19:04 UTC, pholm commented on docs/manual.md
> +    - Käyttämäsi käyttöjärjestelmä (Windows, Macintosh, Linux...)
```suggestion
    - Käyttämäsi käyttöjärjestelmä (Windows, macOS, Linux...)
```

2024-12-02 19:04 UTC, pholm commented on README.md
> +Kipa on alunperin kehitetty Espoolaisten partiolaisten voimin korvaamaan
```suggestion
Kipa on alunperin kehitetty espoolaisten partiolaisten voimin korvaamaan
```

2024-12-02 19:04 UTC, pholm commented on README.md
> +Sakari "Sacu" Koutin koodaamaa Tupa:aa ja vastaamaan ajan haasteisiin.
```suggestion
Sakari "Sacu" Koutin koodaama Tupa ja vastaamaan ajan haasteisiin.
```

2024-12-02 19:04 UTC, pholm commented on docs/installation.md
> +### Tästä eteenpäin 2012 kirjoitettua sisältöä, joka ei välttämättä ole ajantasaista
Poistaisin nämä kaikki pl. Windows-asennus

2024-12-03 08:32 UTC, ilesoft commented on docs/installation.md
> +### Tästä eteenpäin 2012 kirjoitettua sisältöä, joka ei välttämättä ole ajantasaista
hmm, ehkäpä niin. Kopion nämä vain sokeasti tuolta wikin puolelta. Ehkä selkeästi vanhentuneen kaman poisto voidaan nähdä olevan osa uudelleenjärjestelyä.

2024-12-03 08:45 UTC, merged